
/*
Elabore un algoritmo que permita calcular la base de un triángulo. Como datos de entrada se tiene el área y la altura
*/

REAL BASE, AREA, ALTURA

INICIO
	ESCRIBA "--ESTE ALGORITMO CALCULA LA BASE DE UN TRIANGULO-- "
	ESCRIBA "ESCRIBA LA AREA DEL TRIANGULO: "
	LEA AREA
	ESCRIBA "ESCRIBA LA ALTURA DEL TRIANGULO: "
	LEA ALTURA
	
	BASE <- 2 * AREA / ALTURA
	ESCRIBA "LA BASE DEL TRIANGULO ES: ", BASE
FIN